import { z } from 'zod';
import type { LlmClient } from './llm.js';
import type { ThufirConfig } from './config.js';
import type { PositionBook } from './position_book.js';
import { recordEntryGateDecision } from '../memory/llm_entry_gate_log.js';
import { listPerpTradeJournals } from '../memory/perp_trade_journal.js';
import { summarizeSignalPerformance, type SignalPerformanceSummary } from './signal_performance.js';
import { Logger } from './logger.js';

export interface EntryGateCandidate {
  symbol: string;
  side: 'buy' | 'sell';
  notionalUsd: number;
  leverage: number;
  edge: number;
  confidence: number;
  signalClass: string;
  regime: string;
  session: string;
  entryReasoning: string;
  invalidationPrice?: number | null;
  suggestedTtlMinutes?: number;
  expectedRMultiple?: number;
}

export interface EntryGateDecision {
  verdict: 'approve' | 'reject' | 'resize';
  reasoning: string;
  adjustedSizeUsd?: number;
  stopLevelPrice?: number | null;
  equityAtRiskPct?: number;
  targetRR?: number;
}

const DecisionSchema = z.object({
  verdict: z.enum(['approve', 'reject', 'resize']),
  reasoning: z.string(),
  adjustedSizeUsd: z.number().optional(),
  stopLevelPrice: z.number().nullable(),
  equityAtRiskPct: z.number(),
  targetRR: z.number(),
});

const logger = new Logger('info');

function normalizeOptionalFieldPseudoJson(
  raw: string,
  optionalFields: string[]
): string {
  let normalized = raw;
  for (const field of optionalFields) {
    const pattern = new RegExp(`("${field}"\\s*:)\\s*undefined(?=\\s*[,}])`, 'g');
    normalized = normalized.replace(pattern, '$1 null');
  }
  return normalized;
}

function formatBookTable(entries: ReturnType<PositionBook['getAll']>): string {
  if (entries.length === 0) return '(no open positions)';
  const totalNotional = entries.reduce((sum, e) => sum + e.size * e.entryPrice, 0);
  const header = 'symbol | side  | notional  | conc% | thesis expires';
  const divider = '-------|-------|-----------|-------|----------------';
  const rows = entries.map((e) => {
    const notional = e.size * e.entryPrice;
    const concPct = totalNotional > 0 ? ((notional / totalNotional) * 100).toFixed(0) : '0';
    const ttlMin = Math.round((e.thesisExpiresAtMs - Date.now()) / 60_000);
    const ttlStr = ttlMin > 0 ? `${ttlMin}min` : 'EXPIRED';
    return `${e.symbol.padEnd(6)} | ${e.side.padEnd(5)} | $${notional.toFixed(0).padEnd(8)} | ${concPct.padEnd(5)} | ${ttlStr}`;
  });
  const summary = `Total notional: $${totalNotional.toFixed(0)} across ${entries.length} position(s)`;
  return [summary, '', header, divider, ...rows].join('\n');
}

function formatTrackRecord(stats: SignalPerformanceSummary): string {
  if (stats.sampleCount === 0) {
    if (stats.signalClass === 'llm_originator') {
      return `Signal class: llm_originator — this proposal was generated by the LLM originator with an explicit thesis, invalidation price, and R:R estimate. No trade history yet; the track record is building. Judge the thesis quality, the invalidation logic, and the R:R directly. Do not reject solely because sample count is zero.`;
    }
    return `No historical trades for signal class "${stats.signalClass}". Treat as a novel setup — apply extra scrutiny.`;
  }
  const winPct = (stats.thesisCorrectRate * 100).toFixed(0);
  const credibility = stats.sampleCount < 5 ? ' (low sample — high uncertainty)' : '';
  return [
    `Signal class: ${stats.signalClass} — ${stats.sampleCount} trades${credibility}`,
    `Win rate: ${winPct}% | Expectancy: ${stats.expectancy.toFixed(2)} | Sharpe-like: ${stats.sharpeLike.toFixed(2)}`,
    `Avg adverse move: ${stats.maeProxy.toFixed(3)} | Avg favorable move: ${stats.mfeProxy.toFixed(3)}`,
  ].join('\n');
}

function resolveTimeoutMs(config: ThufirConfig): number {
  return Math.max(1, Number(config.autonomy?.llmEntryGate?.timeoutMs ?? 5_000));
}

function shouldRejectOnBothFail(config: ThufirConfig): boolean {
  return config.autonomy?.llmEntryGate?.rejectOnBothFail !== false;
}

function buildPrompt(
  candidate: EntryGateCandidate,
  bookEntries: ReturnType<PositionBook['getAll']>,
  sameSideWarning: string | null,
  signalStats: SignalPerformanceSummary,
): { system: string; user: string } {
  const system = `You are Thufir, an LLM-primary trading agent. Your job is to decide whether to approve, reject, or resize a trade candidate.

The default is no trade. You need a compelling reason to approve. When in doubt, reject.

You are not a quant system. You reason about narrative, market context, and whether this setup makes sense right now.

Respond ONLY with valid JSON matching this schema:
{"verdict":"approve"|"reject"|"resize","reasoning":"...","adjustedSizeUsd":number|undefined,"stopLevelPrice":number|null,"equityAtRiskPct":number,"targetRR":number}

Fields:
- stopLevelPrice: the specific price at which the thesis is invalidated; null if you cannot identify one
- equityAtRiskPct: estimated % of book equity lost if stop is hit (use candidate notional and leverage)
- targetRR: your estimated reward-to-risk ratio for this setup

All four fields (verdict, reasoning, stopLevelPrice, equityAtRiskPct, targetRR) are required. If you cannot fill them, reject.`;

  const bookTable = formatBookTable(bookEntries);

  const warningBlock = sameSideWarning
    ? `\n## ⚠️ Concentration Warning\n\n${sameSideWarning}\n`
    : '';

  const ttlWarning =
    candidate.suggestedTtlMinutes === 60 || candidate.suggestedTtlMinutes === 120
      ? `\n⚠️ TTL is ${candidate.suggestedTtlMinutes}min — a common default. Verify this is thesis-derived, not a placeholder.`
      : '';

  const originatorFields =
    candidate.invalidationPrice != null || candidate.expectedRMultiple != null
      ? [
          `- Originator invalidation price: $${candidate.invalidationPrice}`,
          `- Originator expected R:R: ${candidate.expectedRMultiple}R`,
          `- Originator TTL: ${candidate.suggestedTtlMinutes}min${ttlWarning}`,
        ].join('\n')
      : '';

  const user = `## Current Open Book

${bookTable}
${warningBlock}
## Trade Candidate

- Symbol: ${candidate.symbol}
- Side: ${candidate.side}
- Notional USD: $${candidate.notionalUsd.toFixed(2)}
- Leverage: ${candidate.leverage}x
- Edge: ${(candidate.edge * 100).toFixed(2)}%
- Confidence: ${(candidate.confidence * 100).toFixed(1)}%
- Signal class: ${candidate.signalClass}
- Regime: ${candidate.regime}
- Session: ${candidate.session}
- Entry reasoning: ${candidate.entryReasoning}${originatorFields ? '\n' + originatorFields : ''}

## Signal Performance Context

${formatTrackRecord(signalStats)}

## Instruction

Respond ONLY with valid JSON:
{"verdict":"approve"|"reject"|"resize","reasoning":"<your reasoning>","adjustedSizeUsd":<number if resize, omit otherwise>,"stopLevelPrice":<price that invalidates thesis, or null>,"equityAtRiskPct":<% of book equity lost at stop>,"targetRR":<reward:risk ratio>}`;

  return { system, user };
}

async function callLlm(
  client: LlmClient,
  candidate: EntryGateCandidate,
  bookEntries: ReturnType<PositionBook['getAll']>,
  sameSideWarning: string | null,
  signalStats: SignalPerformanceSummary,
  timeoutMs?: number
): Promise<EntryGateDecision> {
  const { system, user } = buildPrompt(candidate, bookEntries, sameSideWarning, signalStats);
  const response = await client.complete(
    [
      { role: 'system', content: system },
      { role: 'user', content: user },
    ],
    timeoutMs !== undefined ? { timeoutMs } : {}
  );

  const normalized = normalizeOptionalFieldPseudoJson(
    response.content.trim(),
    ['adjustedSizeUsd', 'stopLevelPrice']
  );
  const parsed = JSON.parse(normalized) as Record<string, unknown>;
  if (parsed.adjustedSizeUsd === null) {
    delete parsed.adjustedSizeUsd;
  }
  const validated = DecisionSchema.parse(parsed);
  return {
    verdict: validated.verdict,
    reasoning: validated.reasoning,
    stopLevelPrice: validated.stopLevelPrice,
    equityAtRiskPct: validated.equityAtRiskPct,
    targetRR: validated.targetRR,
    ...(validated.adjustedSizeUsd !== undefined ? { adjustedSizeUsd: validated.adjustedSizeUsd } : {}),
  };
}

function summarizeLlmError(error: unknown): { type: string; message: string } {
  if (error instanceof SyntaxError) {
    return { type: 'json_parse', message: error.message };
  }
  if (error instanceof z.ZodError) {
    return {
      type: 'schema_validation',
      message: error.issues.map((issue) => `${issue.path.join('.') || '(root)'}: ${issue.message}`).join('; '),
    };
  }
  const message = error instanceof Error ? error.message : String(error);
  return { type: 'llm_call', message };
}

export class LlmEntryGate {
  constructor(
    private mainLlm: LlmClient,
    private fallbackLlm: LlmClient,
    private notify: (msg: string) => Promise<void>,
    private book: PositionBook,
    private config: ThufirConfig,
  ) {}

  async evaluate(
    candidate: EntryGateCandidate,
    _markPrice: number,
  ): Promise<EntryGateDecision> {
    // Conflict fast-path: no LLM call needed
    if (this.book.hasConflict(candidate.symbol, candidate.side)) {
      const decision: EntryGateDecision = {
        verdict: 'reject',
        reasoning: 'Opposite-side position already open on this symbol. Cannot open conflicting trade.',
      };
      recordEntryGateDecision({
        symbol: candidate.symbol,
        side: candidate.side,
        notionalUsd: candidate.notionalUsd,
        verdict: decision.verdict,
        reasoning: decision.reasoning,
        adjustedSizeUsd: undefined,
        usedFallback: false,
        signalClass: candidate.signalClass,
        regime: candidate.regime,
        session: candidate.session,
        edge: candidate.edge,
      });
      return decision;
    }

    // Reject originator proposals that didn't name a price invalidation level
    if ('invalidationPrice' in candidate && (candidate.invalidationPrice == null || !Number.isFinite(candidate.invalidationPrice))) {
      const decision: EntryGateDecision = {
        verdict: 'reject',
        reasoning: 'No price invalidation level set — cannot approve a trade without a concrete stop price.',
      };
      recordEntryGateDecision({
        symbol: candidate.symbol,
        side: candidate.side,
        notionalUsd: candidate.notionalUsd,
        verdict: decision.verdict,
        reasoning: decision.reasoning,
        adjustedSizeUsd: undefined,
        usedFallback: false,
        signalClass: candidate.signalClass,
        regime: candidate.regime,
        session: candidate.session,
        edge: candidate.edge,
      });
      return decision;
    }

    const bookEntries = this.book.getAll();
    const signalStats = summarizeSignalPerformance(
      listPerpTradeJournals({ limit: 200 }),
      candidate.signalClass,
    );
    const timeoutMs = resolveTimeoutMs(this.config);
    let usedFallback = false;
    let decision: EntryGateDecision;

    // Build same-side concentration warning if a position in this symbol/side already exists
    const sameSideWarning = this.book.hasPosition(candidate.symbol, candidate.side)
      ? `A ${candidate.side} position in ${candidate.symbol} is ALREADY OPEN in the book. ` +
        `Approving this candidate would stack concentration in the same symbol and direction. ` +
        `Reject unless you can name a specific, concrete reason to increase exposure here right now — ` +
        `not just because the signal fired again.`
      : null;

    // Try main LLM — no timeoutMs cap, matching AgenticOpenAiClient behaviour
    try {
      decision = await callLlm(this.mainLlm, candidate, bookEntries, sameSideWarning, signalStats);
    } catch (error) {
      const summary = summarizeLlmError(error);
      logger.warn('Entry gate main LLM failed; falling back', {
        provider: this.mainLlm.meta?.provider ?? 'unknown',
        model: this.mainLlm.meta?.model ?? 'unknown',
        symbol: candidate.symbol,
        side: candidate.side,
        failureType: summary.type,
        reason: summary.message,
      });
      usedFallback = true;
      try {
        await this.notify('⚠️ Entry gate: using fallback LLM — decision quality may be lower');
      } catch { /* best-effort */ }
      try {
        decision = await callLlm(this.fallbackLlm, candidate, bookEntries, sameSideWarning, signalStats, timeoutMs);
      } catch (fallbackError) {
        const summary = summarizeLlmError(fallbackError);
        logger.warn('Entry gate fallback LLM failed; using safe default', {
          provider: this.fallbackLlm.meta?.provider ?? 'unknown',
          model: this.fallbackLlm.meta?.model ?? 'unknown',
          symbol: candidate.symbol,
          side: candidate.side,
          failureType: summary.type,
          reason: summary.message,
        });
        decision = shouldRejectOnBothFail(this.config)
          ? {
              verdict: 'reject',
              reasoning: 'LLM unavailable — defaulting to reject (safe)',
            }
          : {
              verdict: 'approve',
              reasoning: 'LLM unavailable and rejectOnBothFail=false — allowing execution',
            };
      }
    }

    recordEntryGateDecision({
      symbol: candidate.symbol,
      side: candidate.side,
      notionalUsd: candidate.notionalUsd,
      verdict: decision.verdict,
      reasoning: decision.reasoning,
      adjustedSizeUsd: decision.adjustedSizeUsd,
      usedFallback,
      signalClass: candidate.signalClass,
      regime: candidate.regime,
      session: candidate.session,
      edge: candidate.edge,
      stopLevelPrice: decision.stopLevelPrice,
      equityAtRiskPct: decision.equityAtRiskPct,
      targetRR: decision.targetRR,
    });

    return decision;
  }
}
